name: iamtif
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.1.3 <4.0.0'

dependencies: 
  get: 4.6.6
  firebase_core: ^2.19.0
  firebase_auth: ^4.11.1
  cloud_firestore: 4.11.0
  google_fonts: 6.1.0
  material_design_icons_flutter: 7.0.7296
  flutter_launcher_icons: 0.13.1
  flutter_native_splash: 2.3.4
  flutter_animate: 4.2.0+1
  google_sign_in: 6.1.5
  cloud_functions: ^4.5.1
  firebase_messaging: 14.7.5
  firebase_crashlytics: ^3.4.5
  flutter_local_notifications: ^16.2.0
  sliding_up_panel: ^2.0.0+1
  custom_navigation_bar: ^0.8.2
  intl: ^0.19.0
  carousel_slider: 4.2.1
  flutter: 
    sdk: flutter
  expandable_text: ^2.3.0

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/images/
    - assets/icon/
    - assets/json/
  uses-material-design: true

flutter_launcher_icons: 
  android: launcher_icon
  image_path: assets/icon/logo_io.png
  web: 
    image_path: assets/icon/logo_io.png
    background_color: '#hexcode'
    theme_color: '#hexcode'
    generate: true
  windows: 
    image_path: assets/icon/logo_io.png
    generate: true
    icon_size: 48
  macos: 
    image_path: assets/icon/logo_io.png
    generate: true
  ios: true
  min_sdk_android: 21

